twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: [
        'form/product_variant.html.twig',
        'form/category_slider.html.twig',
        'form/header_cart.item.html.twig'
    ]
    globals:
        locales: '%app.locales%'
        tajeerFees: '%tajeerFees%'

when@test:
    twig:
        strict_variables: true
